"""empty message

Revision ID: 088db89dc0f2
Revises: 72bec85aab36
Create Date: 2025-07-10 08:48:47.066816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088db89dc0f2'
down_revision = '72bec85aab36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
