"""empty message

Revision ID: 465ddf0b6bfd
Revises: 0d25ed4f5762
Create Date: 2025-08-08 12:09:14.443406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465ddf0b6bfd'
down_revision = '0d25ed4f5762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
